name: Continuous integration
on: [push, pull_request]

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt

      - name: Run `fmt`
        run: |
          cargo fmt --all
        
      - name: Commit and push
        run: |
          git config --global user.name ${{ secrets.NAME }}
          git config --global user.email ${{ secrets.EMAIL }}
          git add . && git diff --staged --quiet || git commit -m "Format with `cargo fmt`"
          git push
  
  lint:
    name: Lint
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy

      - name: Run `clippy`
        run: |
          cargo clippy -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: format
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Run tests
        run: |
          cargo test